version: "3"

services: 
    frontend: 
        build: ./frontend
        container_name: realworld-docker-frontend
        command: serve -s build -l 3000 
        restart: unless-stopped

    api:
        build: ./api
        container_name: realworld-docker-api
        command: npm run start
        restart: unless-stopped
        environment: 
            - PORT=3001 
            - HOST=http://realworld.com
            - MONGO_URL=mongodb://api_db:27017/api
            - AUTH_API_URL=http://auth:3002/api
        ports: 
            - "3001:3001"
        depends_on: 
            - api_db
    auth:
        build: ./auth
        container_name: realworld-docker-auth-api
        command: npm run start
        restart: unless-stopped
        environment: 
            - PORT=3002
            - HOST=http://realworld.com
            - MONGO_URL=mongodb://auth_db:27017/auth
        ports: 
            - "3002:3002"
        depends_on: 
            - auth_db
    api_db:
        image: mongo:latest
        container_name: realworld-docker-api-db
        volumes: 
            - mongodb_api:/data/db
    auth_db:
        image: mongo:latest
        container_name: realworld-docker-auth-db
        volumes: 
            - mongodb_auth:/data/db
    nginx: 
        image: nginx:stable-alpine
        container_name: realworld-docker-nginx
        ports: 
            - "80:80"
        volumes: 
            - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
        depends_on: 
            - frontend


volumes: 
    mongodb_api:
    mongodb_auth:
